ARG PYTORCH_RELEASE="23.08"
ARG PYTHON_VERSION="3"

FROM "nvcr.io/nvidia/pytorch:${PYTORCH_RELEASE}-py${PYTHON_VERSION}"

EXPOSE 11434/tcp
WORKDIR /usr/local/bin

RUN pip install --upgrade pip \ 
    pip install --no-cache-dir transformers \
    langchain \
    pymysql

RUN apt-get update && apt-get install -y \
    git \
    mysql-server \
    && rm -rf /var/lib/apt/lists/*

RUN curl https://ollama.ai/install.sh | sh

WORKDIR /app
RUN mkdir ./noah \
    && mkdir ./noah/data

# Configure MySQL (Later use)
# RUN service mysql start && \
#    mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION; FLUSH PRIVILEGES;" && \
#    mysql -e "CREATE DATABASE IF NOT EXISTS ColorPalette;" \
#    mysql -e "CREATE DATABASE IF NOT EXISTS Coop;" \
#    mysql -e "CREATE DATABASE IF NOT EXISTS LLMold;"
