ARG PYTORCH_RELEASE="23.08"
ARG PYTHON_VERSION="3"

FROM python:3.9-slim

ARG NOAH_WORK_DIR
ARG LANG_SERVER_NAME
ARG LANG_SERVER_PORT
ARG EXTERNAL_SERVER_NAME
ARG EXTERNAL_SERVER_PORT
ARG NOAH_PROXY_PORT
ARG NETWORK_NAME

ENV NOAH_WORK_DIR=${NOAH_WORK_DIR}
ENV LANG_SERVER_NAME=${LANG_SERVER_NAME}
ENV LANG_SERVER_PORT=${LANG_SERVER_PORT}
ENV EXTERNAL_SERVER_NAME=${EXTERNAL_SERVER_NAME}
ENV EXTERNAL_SERVER_PORT=${EXTERNAL_SERVER_PORT}
ENV NOAH_PROXY_PORT=${NOAH_PROXY_PORT}
ENV NETWORK_NAME=${NETWORK_NAME}

EXPOSE 6060/tcp
WORKDIR /usr/local/bin

RUN pip install --upgrade pip
RUN pip install --no-cache-dir pyyaml \
    docker \
    nvidia-ml-py \
    Flask
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN mkdir ./llm_proxy

COPY ./llm_proxy /app/llm_proxy

WORKDIR /app/llm_proxy
CMD ["python", "noah_proxy.py"]
